language: c

matrix:
  include:
    - os: freebsd
      compiler:
        - clang
        - gcc
    - os: linux
      arch: s390x
      dist: bionic
      addons:
        apt:
          update: true
          packages:
          - gcc
          - libncursesw5
          - libncursesw5-dev
      compiler:
        - clang
        - gcc

script:
  - ./autogen.sh
  # clang might warn about C11 generic selections in isnan()
  - CFLAGS=-Wno-c11-extensions ./configure --enable-werror
  - make -k
  - CFLAGS=-Wno-c11-extensions make distcheck DISTCHECK_CONFIGURE_FLAGS=--enable-werror
